name: marchehaitien
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0" # Spécifier la version minimale de Dart 2.17

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.0.0
  firebase_core: ^3.1.0
  firebase_database: ^11.1.6
  intl_phone_field: ^3.2.0
  image_picker: ^0.8.5+3
  file_picker: ^8.1.5
  cloud_firestore: ^5.5.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.0.20
  firebase_storage: ^12.3.6
  http: ^1.2.2
  html: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/background.png
    - assets/default_user.jpeg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

file_picker:
  platforms:
    android: true
    ios: true
    linux: false
    macos: false
    windows: false
